name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020
 
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-npmv3-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-npmv3-
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Node Dependencies
        run: |
          yarn install
      - name: Build Webpack
        run: |
          npm run build_wp
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gemsv3-${{ hashFiles('**/Gemfile') }}-${{ hashFiles('_config.yml') }}
          restore-keys: |
            ${{ runner.os }}-gemsv3-
      - name: Trust github workspace
        run:
          git config --global --add safe.directory /github/workspace
      - name: Main Jekyll Build
        uses: helaili/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_history: true
          target_path: /
          pre_build_commands: git config --global --add safe.directory /github/workspace
      - name: Get Short Hash
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Versioned Jekyll Build
        uses: helaili/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_history: true
          target_path: versions/${{ steps.vars.outputs.sha_short }}
          pre_build_commands: git config --global --add safe.directory /github/workspace
